### ISSUE TITLE
Unable to find Issuer Certificate

### ISSUE THREAD

**Issue by pandalec** [gematik/ref-eRp-FD-Server#10]
Hey!

First of all, thanks for the update! Server is up and running. I used your provided howto (https://github.com/gematik/ref-eRp-FD-Server/issues/8#issuecomment-726045883) and the new server/certificate configuration from readme.md but now I receive a:

`Error: {"resourceType":"OperationOutcome","meta":{"profile":["http://hl7.org/fhir/StructureDefinition/OperationOutcome"]},"issue":[{"severity":"error","code":"invalid","details":{"text":"Unable to verify CMS container: Unable to find Issuer Certificate!"}}]}`

Started server with:

```
cargo run -p ref-erx-fd-server -- \ 
    --enc-key fd_id_enc \
    --enc-cert fd_id_enc.cert \
    --sig-key fd_id_sig \
    --sig-cert fd_id_sig.cert \
    --token file://./idp_id.pub \
    --tsl https://download.tsl.ti-dienste.de/TSL.xml \
    --listen 0.0.0.0:3000

     Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/ref-erx-fd-server --enc-key fd_id_enc --enc-cert fd_id_enc.cert --sig-key fd_id_sig --sig-cert fd_id_sig.cert --token 'file://./idp_id.pub' --tsl 'https://download.tsl.ti-dienste.de/TSL.xml' --listen '0.0.0.0:3000'`
2020-12-08T15:13:11.111891+01:00 INFO actix_server::builder - Starting 8 workers
2020-12-08T15:13:11.112685+01:00 INFO actix_server::builder - Starting "actix-web-service-0.0.0.0:3000" service on 0.0.0.0:3000
2020-12-08T15:13:11.412882+01:00 INFO ref_erx_fd_server::tasks::tsl::update - TSL updated: https://download.tsl.ti-dienste.de/TSL.xml
2020-12-08T15:13:41.061920+01:00 INFO access_log - HTTP/1.1 POST - 127.0.0.1:58083 - /Task/$create
2020-12-08T15:13:41.367313+01:00 INFO access_log - HTTP/1.1 POST - 127.0.0.1:58085 - /Task/13814002-1dd2-11b2-802a-3979a04ef018/$activate
```

Any idea what I am doing wrong? Thank you!

Best regards,
parsi

**Comment by nauni77** [comment]
Hello, we have the same issue. Can you please help? Thanks in advance, Oli

**Comment by gematik1** [comment]
Hi Parsi,
this is because of bundle resource sent within $accept operation needs to be signed with a qualified signature. Such signature is verified to be issued by some CA certificate contained in official list of trustful certificates by German national authority Bundesnetzagentur. The trust service list (TSL) used at server startup by --tsl parameter points to this official list.

In order to make it possible to test without an official qualified signature you can pass a test version of such a list during server startup by adding --bnetza parameter followed by a file url of such a list. An example of such a file you can find in example folder. It is named Pseudo-BNetzA-VL-seq24.xml. 

We're currently preparing a description how to set up a configuration for such a private PKI.

Best regards,
Gematik Dev Team

**Comment by gematik1** [comment]
Hi Parsi,

To get your self generated QES signing certificate to be trusted by the server add it to the BNetzA-VL file which is passed to the server during startup by parameter `--benetza`.

In order to do so, add the following lines after the last occurence of TSPService in BNetzA-VL. You can use the example file BNetzA-VL-seq24.xml (currently after line 98531).

```
<TSPService>
    <ServiceInformation>
        <ServiceTypeIdentifier>
            http://uri.etsi.org/TrstSvc/Svctype/CA/QC2
        </ServiceTypeIdentifier>
        <ServiceDigitalIdentity>
            <DigitalId>
                <X509Certificate>
                    ADD_CUSTOM_CERTIFICATE_HERE
                </X509Certificate>
            </DigitalId>
        </ServiceDigitalIdentity>
        <ServiceStatus>
            http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted
        </ServiceStatus>
        <StatusStartingTime>
            2020-01-01T00:00:00Z
        </StatusStartingTime>
    </ServiceInformation>
</TSPService>

```
Replace "[ADD_CUSTOM_CERTIFICATE_HERE](url)" with your self generated certficate. If you followed chapter "[Generating Credentials](https://github.com/gematik/ref-eRp-FD-Server#generating-credentials)" instructions, your QES certificate could be found in `qes_id.cert`. Make sure to drop the "`-----BEGIN CERTIFICATE-----`" and "`-----END CERTIFICATE----`-" lines and remove all line breaks. The replacement for "[ADD_CUSTOM_CERTIFICATE_HERE](url)" must be a single line.

This solution only works until the BNetzA-VL signature is verified by the server which we will implement in one of the next releases. 

Best regards,
Gematik Dev Team
