### ISSUE TITLE
Documentation does not map release 0.4.0

### ISSUE THREAD

**Issue by erickubenka** [gematik/ref-eRp-FD-Server#3]
Hi there, 

as using 0.3.0 release last week und updating source code to 0.4.0 today, I encountered an issue on startup with following error:

```bash
error: The following required arguments were not provided:
    --kbv-cert <kbv-cert>

USAGE:
    ref-erx-fd-server --cert <cert> --kbv-cert <kbv-cert> --key <key> --config <log-config> --listen <server-addr> --token <token> --tsl <tsl>
```

The new parameter `kbv-cert`  ist currently not documented in `README.md` guide, as well as which type of certificate must be provided. So I created a new X509 certificate following the instructions for the `fd_id` certificate and tried it.
It seems to work.

Should I send you a PR for this or will you go to update it by yourself?

Best regards
Eric

**Comment by Gematik-Entwicklung** [comment]
Hi @erickubenka,

thanks for the hint and sorry for the trubble. We've already noticed, that the documentation is inclomplete and fixed this in our internal repositories. So this issue will be fixed in the next release.

The KBV certificate is a normal X.509 certificate that is used to verify the integrity of the KBV bundle passed in the Task Activate Parameters used in the Task Activate Operation.

Bet regards,
Gematik Dev Team.
