### ISSUE TITLE
Question regarding QES and base64xml

### ISSUE THREAD

**Issue by pandalec** [gematik/ref-eRp-FD-Server#7]
Good morning,
me again :) I've got a question regarding signing base64xml. Api documentation says:
```
<ns10:Document ID="QES550918322" ShortText="KBV-FHIR-Verordnung.xml">
	<ns8:Base64XML>PEJ1[...]GxlPg==</ns8:Base64XML>
</ns10:Document>
```
You are offering inside this repo a tool which handles QES on the eRp bundle and AFAIK there's currently no Konnektor which is able to QES sign `<Base64XML>`. So my questions is, will the API change to `<Base64Data>` or will there be a Konnektor update which handles the QES part?

Best regards,
parsi

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

you were basically right, older vesions of Konnektor didn't support qualified signatures. Currently we are rolling out ProductTypeVersion "PTV" 3 which will produce qualified signatures in CAdES-Containers and you need to input the XML base64-encoded.

The following versions (and above) from the three Konnektor manufacturers must be used:
- secunet Konnektor 2.1.0
- KoCoBOX MED+ 2.3.24:2.0.0
- RISE Konnektor 2.1.0:1.0.0

Best regards,
gematik Dev-Team.

**Comment by pandalec** [comment]
Hi Dev Team!
Thanks again for your response. AFAIK secunet Konnektor 3.5.x is mandatory for PTV3, don't know about the others yet. But my point was that using 
```
<ns10:Document ID="QES550918322" ShortText="KBV-FHIR-Verordnung.xml">
	<ns8:Base64XML>PEJ1[...]GxlPg==</ns8:Base64XML>
</ns10:Document>
```
is currently not working because of missing CADES for Base64XML type inside Konnektor spec. Only blobs are allowed. Therefore I had to use
```
<ns10:Document ID="QES550918322" ShortText="CADES">
	<Base64Data MimeType="text/plain;charset=utf-8">PEJ1[...]GxlPg==</Base64Data>
</ns10:Document>
```

Best regards,
parsi

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

you can use Base64Data instead of Base64XML with the secunet Konnektor. However, we strongly advise against it, because the other Konnektors only support Base64XML in Base64 representation.

Unfortunately we're only responsible for ref-erx-fd-server here, so if you need more detailed information on the problem you described, it might be better to open an issue in one of the following projects:

- https://github.com/gematik/api-telematik
- https://github.com/gematik/examples-TelematikInterfaces

Best regards,
gematik Dev-Team
